# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
#          algorithm: sha1
#          encode_as_base64: false
#          iterations: 1

#        AppBundle\Entity\User:
#            algorithm: sha1
#            encode_as_base64: false
#            iterations: 1

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    hector:
                        #ytJBcNm3cHmN
                        password: $2y$12$gzFW9LUyP/70B6ULJqfWieyRKqQy6Va57k.5nLcjzJVn5bqVN3FdG
                        roles: 'ROLE_USER'

                    user1:
                        #ytJBcNm3cHmN
                        password: $2y$12$gzFW9LUyP/70B6ULJqfWieyRKqQy6Va57k.5nLcjzJVn5bqVN3FdG
                        roles: 'ROLE_USER'
                    user2:
                        #xzqTOPfG1PW1
                        password: a9d30fc000a2e2e4f83a0ffa327cf2a4c2e1aa1d
                        roles: 'ROLE_USER'

#        registered_users:
#            entity:
#                class: AppBundle:User
#                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#            guard:
#                authenticators:
#                    - app.form_login_authenticator

#            pattern: ^/posts
#            http_basic: ~

            anonymous: ~
#            form_login:
#                login_path: /user/login
#                check_path: /login_check
#                post_only: true
#                default_target_path: /posts
#                always_use_default_target_path: true
#                failure_path: /user/login

    access_control:
#        - { path: ^/posts, roles: ROLE_USER }
#        - { path: ^/user, roles: ROLE_USER }


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
