parameters:
    tokens: value 12345

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.aws_s3:
        class: AppBundle\Service\AwsS3Service

    app.aws_s3:
        class: AppBundle\Service\AwsElasticCacheService

    app.tokens.action_listener:
        class: AppBundle\EventListener\TokenListener
        arguments: ['%tokens%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    app.post_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Post

    app.post_service:
        class: AppBundle\Service\PostService
        arguments: ["@app.post_repository"]

    app.user_repository:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - AppBundle\Entity\User

    app.user_service:
        class: AppBundle\Service\UserService
        arguments: ["@app.user_repository"]

    app.pagination_service:
            class: AppBundle\Service\PaginationService

    app.form_login_authenticator:
            class: AppBundle\Security\FormLoginAuthenticator
            arguments: ["@router", "@security.password_encoder"]