parameters:
    tokens: value 12345

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.aws_s3_wrapper:
        class: AppBundle\Wrapper\Aws\S3Wrapper
        arguments: ["%aws_s3_bucket_upload%"]

    app.aws_sns_wrapper:
        class: AppBundle\Wrapper\Aws\SnsWrapper
        arguments: ["%aws_sns_arn%"]

    app.aws_sqs_wrapper:
        class: AppBundle\Wrapper\Aws\SqsWrapper
        arguments: ["%aws_sqs_queue%"]

    app.local_storage_wrapper:
        class: AppBundle\Wrapper\LocalStorageWrapper

    app.event_service:
        class: AppBundle\Service\EventService
        arguments: ["@app.aws_sqs_wrapper"]

    app.notification_service:
        class: AppBundle\Service\NotificationService
        arguments: ["@app.aws_sns_wrapper"]

    app.cloud_storage_service:
        class: AppBundle\Service\StorageService
        arguments: ["@app.aws_s3_wrapper"]

    app.local_storage_service:
        class: AppBundle\Service\StorageService
        arguments: ["@app.local_storage_wrapper"]

    app.tokens.action_listener:
        class: AppBundle\EventListener\TokenListener
        arguments: ['%tokens%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    app.post_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Post

    app.post_service:
        class: AppBundle\Service\PostService
        arguments: ["@app.post_repository", "@app.event_service", "@app.local_storage_service", "@app.cloud_storage_service"]

    app.user_repository:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - AppBundle\Entity\User

    app.user_service:
        class: AppBundle\Service\UserService
        arguments: ["@app.user_repository"]

    app.pagination_service:
            class: AppBundle\Service\PaginationService

    app.form_login_authenticator:
            class: AppBundle\Security\FormLoginAuthenticator
            arguments: ["@router", "@security.password_encoder"]